# Generated by Django 5.1.1 on 2025-01-13 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='sender_team',
            field=models.ForeignKey(default='83328720-2dc4-4cf3-aca1-a8535148e329', on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='workspaces.team'),
        ),
    ]
