# Generated by Django 5.1.1 on 2025-01-13 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0002_submission_sender_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='sender_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='workspaces.team'),
        ),
    ]
