# Generated by Django 5.1.1 on 2025-02-15 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='text_content',
            new_name='content',
        ),
    ]
